version: "3"
services:
  db:
    image: elestio/postgres:15
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    ports:
      - "172.17.0.1:30805:5432"

  odoo:
    image: elestio/odoo:${SOFTWARE_VERSION_TAG}
    restart: always
    depends_on:
      - db
    ports:
      - "172.17.0.1:8871:8069"
    tty: true
    command: -- --dev=reload
    volumes:
      - ./addons:/mnt/extra-addons
      - ./config:/etc/odoo
      - ./odoo_www:/var/lib/odoo
    logging:
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

  pgadmin4:
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${ADMIN_PASSWORD}
      PGADMIN_LISTEN_PORT: 8080
    ports:
      - "172.17.0.1:4723:8080"
    volumes:
      - ./servers.json:/pgadmin4/servers.json
