version: '3'
services:
  db:
    image: postgres:13
    container_name: db
    restart: always
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
        - ./postgresql:/var/lib/postgresql/data
    logging:
      driver: "json-file"
      options:
          max-file: "5"
          max-size: "10m"
  odoo:
    image: odoo:${SOFTWARE_VERSION_TAG}
    container_name: odoo
    restart: always
    depends_on:
      - db
    ports:
      - "172.17.0.1:8871:8069"
    tty: true
    command: -- --dev=reload
    volumes:
      - ./addons:/mnt/extra-addons
      - ./config:/etc/odoo
    logging:
      driver: "json-file"
      options:
          max-file: "5"
          max-size: "10m"
networks:
  postgres:
    driver: bridge          
